#!/bin/bash
set -f
# LIST is the list of characters to try
LIST1="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z "
LIST2="0 1 2 3 4 5 6 7 8 9 "
LIST3="a b c d e f g h i j k l m n o p q r s t u v w x y z "
LIST4="~ @ # $ % ^ * _ + - = { } [ ] ? ; : "
LIST5="~ @ # $ % ^ * _ + - = { } [ ] ? ; : "
#extracts the hash and salt value
encr=`grep b13 shadow.test | cut -c 7-17`
salt=`grep b13 shadow.test | cut -c 5-6`
#list and generates all possible characters to become a 5 characters password
for a in $LIST1
  do
   for b in $LIST2
    do
      for c in $LIST3
       do
         for d in $LIST4
          do
	    for e in $LIST5
	     do
	       echo -n "$a$b$c$d$e "   
#it will compare between extracted hash and original hash value. If they are same, the password will save into the b_output.txt. if not it will keep running until same hash value.
  test=`mkpasswd -m des "$a$b$c$d$e" -s $salt | cut -c 3-13`
		if [ $test == $encr ] ; then
		echo "Password is "$a$b$c$d$e" salt values is $salt Hash values is $encr" >b_output.txt		
			exit
		fi
	    done
         done
      done
   done
done
